### Buscar todo os ID
GET http://localhost:3000/user/

### Buscar ID especifico
GET http://localhost:3000/user/"id"

### Inserir Informação no banco
POST http://localhost:3000/user/
content-type: application/json

{
  "name": "Robson",
  "endereco": "Rua n sei",
  "cep": "312312-312",
  "cpf": "123.345.678.00",
  "saldo": "50"
}

### Deletar um usuario pelo ID no banco
DELETE http://localhost:3000/user/

### Atualizar um usuario pelo ID no Banco
PUT http://localhost:3000/user/86fbd27d-5e60-4840-b0bb-24a90e336cda
content-type: application/json

{
  "name": "Robson",
  "endereco": "Rua esqueci",
  "cep": "312312-900",
  "cpf": "123.345.999.00"
}

### Busca o saldo de uma conta
GET http://localhost:3000/user/saldo/43f90661-4f34-48f5-8977-8b7abf748524
